-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: public.customer
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE TABLE public.customer (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint NOT NULL,
    email text NOT NULL,
    first_name text,
    last_name text,
    full_name text GENERATED ALWAYS AS (((COALESCE(first_name, ''::text) || ' '::text) || COALESCE(last_name, ''::text))) STORED,
    balance numeric(12,2) DEFAULT 0 NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id),
    CONSTRAINT customer_email_key UNIQUE (email),
    CONSTRAINT customer_org_id_fkey FOREIGN KEY (org_id) REFERENCES org(id) ON DELETE CASCADE,
    CONSTRAINT customer_balance_chk CHECK (balance >= 0::numeric),
    CONSTRAINT customer_status_chk CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'banned'::text]))
);

COMMENT ON TABLE public.customer IS 'Customers belonging to an organisation';
