-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: public.org
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE TABLE public.org (
    id bigint GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT org_pkey PRIMARY KEY (id),
    CONSTRAINT org_name_key UNIQUE (name)
);

COMMENT ON TABLE public.org IS 'Organisations';
COMMENT ON COLUMN public.org.name IS 'Unique display name';
