-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.audit_trigger()
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE OR REPLACE FUNCTION public.audit_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    INSERT INTO audit_log (table_name, action)
    VALUES (TG_TABLE_NAME, TG_OP);
    RETURN NEW;
END;
$function$;
