-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.deactivate_customer(IN p_id bigint)
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE OR REPLACE PROCEDURE public.deactivate_customer(IN p_id bigint)
 LANGUAGE plpgsql
AS $procedure$
BEGIN
    UPDATE customer SET status = 'inactive' WHERE id = p_id;
END;
$procedure$;
