-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.full_display_name(p_first text, p_last text)
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE OR REPLACE FUNCTION public.full_display_name(p_first text, p_last text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
    SELECT trim(coalesce(p_first, '') || ' ' || coalesce(p_last, ''));
$function$;
