"""Unit tests for the SQL generation layer (no database required)."""

from __future__ import annotations

from pgcarter.models import Column, Table
from pgcarter.sql import generators as gen
from pgcarter.sql.base import quote_ident, with_header


def test_quote_ident_simple_unquoted():
    assert quote_ident("customer") == "customer"


def test_quote_ident_reserved_and_mixed_case():
    assert quote_ident("user") == '"user"'
    assert quote_ident("MyTable") == '"MyTable"'
    assert quote_ident('weird"name') == '"weird""name"'


def test_table_sql_is_executable_create_table(sample_table):
    sql = gen.table_sql(sample_table)
    assert sql.startswith("CREATE TABLE public.customer (")
    assert "id bigint GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "created_at timestamptz DEFAULT now() NOT NULL" in sql
    assert "full_name text GENERATED ALWAYS AS (email) STORED" in sql
    assert "CONSTRAINT customer_pkey PRIMARY KEY (id)" in sql
    assert sql.rstrip().endswith(";")


def test_table_constraints_are_ordered_pk_first(sample_table):
    sql = gen.table_sql(sample_table)
    pk = sql.index("PRIMARY KEY")
    uniq = sql.index("UNIQUE (email)")
    fk = sql.index("FOREIGN KEY")
    assert pk < uniq < fk


def test_table_comments_emitted():
    table = Table(
        schema="public",
        name="t",
        owner="o",
        comment="hello 'world'",
        columns=[Column(name="c", position=1, data_type="int", nullable=True, comment="a column")],
    )
    sql = gen.table_sql(table)
    assert "COMMENT ON TABLE public.t IS 'hello ''world''';" in sql
    assert "COMMENT ON COLUMN public.t.c IS 'a column';" in sql


def test_index_sql_terminated(sample_inventory):
    idx = sample_inventory.indexes[1]
    assert gen.index_sql(idx).endswith(";")
    assert gen.index_sql(idx).startswith("CREATE INDEX")


def test_view_sql_create_view(sample_inventory):
    sql = gen.view_sql(sample_inventory.views[0])
    assert sql.startswith("CREATE VIEW public.active_customer AS")
    assert sql.rstrip().endswith(";")


def test_function_sql_includes_definition(sample_inventory):
    sql = gen.function_sql(sample_inventory.functions[0])
    assert "CREATE OR REPLACE FUNCTION public.greet" in sql
    assert sql.rstrip().endswith(";")


def test_extensions_sql_idempotent(sample_inventory):
    sql = gen.extensions_sql(sample_inventory.extensions)
    assert "CREATE EXTENSION IF NOT EXISTS pgcrypto" in sql


def test_sequence_sql(sample_inventory):
    sql = gen.sequence_sql(sample_inventory.sequences[0])
    assert "CREATE SEQUENCE IF NOT EXISTS public.customer_id_seq" in sql
    assert "OWNED BY public.customer.id" in sql


def test_roles_sql(sample_inventory):
    sql = gen.roles_sql(sample_inventory.roles)
    assert "CREATE ROLE app WITH" in sql
    assert "LOGIN" in sql


def test_grant_statements(sample_inventory):
    stmts = gen.grant_statements(sample_inventory.grants)
    text = "\n".join(stmts)
    assert "GRANT USAGE ON SCHEMA public TO app;" in text
    assert "GRANT SELECT ON TABLE public.customer TO readonly;" in text
    assert "GRANT CONNECT ON DATABASE shop TO PUBLIC;" in text


def test_header_block_present():
    out = with_header("db", "obj", "2026-01-01T00:00:00Z", "SELECT 1;")
    assert out.startswith("-- Generated by pgcarter\n")
    assert "-- Database: db" in out
    assert "-- Object: obj" in out
    assert "-- Generated: 2026-01-01T00:00:00Z" in out


def test_generation_is_deterministic(sample_table):
    assert gen.table_sql(sample_table) == gen.table_sql(sample_table)
