"""Tests for the SQL/JSON/graph writers."""

from __future__ import annotations

import json

from pgcarter.report import Report
from pgcarter.writers import write_outputs

TS = "2026-01-01T00:00:00Z"


def test_write_outputs_layout(tmp_path, sample_inventory):
    report = Report()
    write_outputs(
        sample_inventory,
        sql_dir=tmp_path / "sql",
        json_dir=tmp_path / "json",
        timestamp=TS,
        report=report,
    )

    assert (tmp_path / "sql" / "database.sql").is_file()
    assert (tmp_path / "sql" / "extensions.sql").is_file()
    assert (tmp_path / "sql" / "roles.sql").is_file()
    assert (tmp_path / "sql" / "schemas" / "public.sql").is_file()

    table_sql = tmp_path / "sql" / "schemas" / "public" / "tables" / "customer.sql"
    assert table_sql.is_file()
    assert "CREATE TABLE public.customer" in table_sql.read_text()

    # The primary-key index is created by the table; it must NOT have its own file.
    idx_dir = tmp_path / "sql" / "schemas" / "public" / "indexes"
    written = {p.name for p in idx_dir.glob("*.sql")}
    assert "customer_email_idx.sql" in written
    assert "customer_pkey.sql" not in written


def test_json_outputs(tmp_path, sample_inventory):
    report = Report()
    write_outputs(
        sample_inventory,
        sql_dir=tmp_path / "sql",
        json_dir=tmp_path / "json",
        timestamp=TS,
        report=report,
    )
    db = json.loads((tmp_path / "json" / "database.json").read_text())
    assert db["name"] == "shop"

    tables = json.loads((tmp_path / "json" / "tables.json").read_text())
    assert tables[0]["name"] == "customer"
    assert len(tables[0]["columns"]) == 4

    rels = json.loads((tmp_path / "json" / "relationships.json").read_text())
    assert rels[0]["type"] == "foreign_key"


def test_relationships_dot(tmp_path, sample_inventory):
    report = Report()
    write_outputs(
        sample_inventory,
        sql_dir=tmp_path / "sql",
        json_dir=tmp_path / "json",
        timestamp=TS,
        report=report,
    )
    dot = (tmp_path / "json" / "relationships.dot").read_text()
    assert dot.startswith("digraph relationships {")
    assert '"public.customer" -> "public.org"' in dot


def test_headers_on_sql_files(tmp_path, sample_inventory):
    report = Report()
    write_outputs(
        sample_inventory,
        sql_dir=tmp_path / "sql",
        json_dir=tmp_path / "json",
        timestamp=TS,
        report=report,
    )
    content = (tmp_path / "sql" / "database.sql").read_text()
    assert content.startswith("-- Generated by pgcarter")
    assert "report" not in report.errors
    assert report.generated_files
