"""Tests for the Jinja2 documentation renderer."""

from __future__ import annotations

from pathlib import Path

from pgcarter.docs import DocumentationRenderer
from pgcarter.report import Report

TS = "2026-01-01T00:00:00Z"


def _templates(tmp_path: Path) -> Path:
    real = Path(__file__).resolve().parents[1] / "templates"
    return real


def test_renderer_produces_expected_docs(tmp_path, sample_inventory):
    docs = tmp_path / "docs"
    report = Report()
    DocumentationRenderer(_templates(tmp_path), docs, TS, report).render(sample_inventory)

    index = docs / "index.md"
    assert index.is_file()
    text = index.read_text()
    assert "# shop — Database Inventory" in text
    assert text.startswith("<!--\nGenerated by pgcarter\n")

    table_doc = docs / "schemas" / "public" / "tables" / "customer.md"
    assert table_doc.is_file()
    assert "# Table: public.customer" in table_doc.read_text()

    func_doc = docs / "schemas" / "public" / "functions" / "greet.md"
    assert func_doc.is_file()


def test_missing_template_warns_and_continues(tmp_path, sample_inventory):
    tdir = tmp_path / "templates"
    tdir.mkdir()
    # only provide index.md.j2
    (tdir / "index.md.j2").write_text("# {{ database.name }}\n")
    docs = tmp_path / "docs"
    report = Report()

    DocumentationRenderer(tdir, docs, TS, report).render(sample_inventory)

    assert (docs / "index.md").is_file()
    assert not (docs / "database.md").exists()
    assert any("database.md.j2" in w for w in report.warnings)


def test_doc_header_contains_metadata(tmp_path, sample_inventory):
    docs = tmp_path / "docs"
    report = Report()
    DocumentationRenderer(_templates(tmp_path), docs, TS, report).render(sample_inventory)
    header = (docs / "database.md").read_text()
    assert "Database: shop" in header
    assert f"Generated: {TS}" in header


def test_renderer_generates_no_sql(tmp_path, sample_inventory):
    docs = tmp_path / "docs"
    report = Report()
    DocumentationRenderer(_templates(tmp_path), docs, TS, report).render(sample_inventory)
    for md in docs.rglob("*.md"):
        # Markdown docs may reference SQL in fenced blocks, but never end in .sql
        assert md.suffix == ".md"
