-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.active_customers
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.active_customers TO app_readonly;
GRANT DELETE ON TABLE public.active_customers TO sqldump;
GRANT INSERT ON TABLE public.active_customers TO sqldump;
GRANT REFERENCES ON TABLE public.active_customers TO sqldump;
GRANT SELECT ON TABLE public.active_customers TO sqldump;
GRANT TRIGGER ON TABLE public.active_customers TO sqldump;
GRANT TRUNCATE ON TABLE public.active_customers TO sqldump;
GRANT UPDATE ON TABLE public.active_customers TO sqldump;
