-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.audit_log
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.audit_log TO app_readonly;
GRANT DELETE ON TABLE public.audit_log TO sqldump;
GRANT INSERT ON TABLE public.audit_log TO sqldump;
GRANT REFERENCES ON TABLE public.audit_log TO sqldump;
GRANT SELECT ON TABLE public.audit_log TO sqldump;
GRANT TRIGGER ON TABLE public.audit_log TO sqldump;
GRANT TRUNCATE ON TABLE public.audit_log TO sqldump;
GRANT UPDATE ON TABLE public.audit_log TO sqldump;
