-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.customer
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT (email) ON TABLE public.customer TO app_readonly;
GRANT SELECT (id) ON TABLE public.customer TO app_readonly;
GRANT SELECT ON TABLE public.customer TO app_readonly;
GRANT DELETE ON TABLE public.customer TO app_readwrite;
GRANT INSERT ON TABLE public.customer TO app_readwrite;
GRANT SELECT ON TABLE public.customer TO app_readwrite;
GRANT UPDATE ON TABLE public.customer TO app_readwrite;
GRANT DELETE ON TABLE public.customer TO sqldump;
GRANT INSERT ON TABLE public.customer TO sqldump;
GRANT REFERENCES ON TABLE public.customer TO sqldump;
GRANT SELECT ON TABLE public.customer TO sqldump;
GRANT TRIGGER ON TABLE public.customer TO sqldump;
GRANT TRUNCATE ON TABLE public.customer TO sqldump;
GRANT UPDATE ON TABLE public.customer TO sqldump;
