-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.customer_counts
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.customer_counts TO app_readonly;
GRANT DELETE ON TABLE public.customer_counts TO sqldump;
GRANT INSERT ON TABLE public.customer_counts TO sqldump;
GRANT REFERENCES ON TABLE public.customer_counts TO sqldump;
GRANT SELECT ON TABLE public.customer_counts TO sqldump;
GRANT TRIGGER ON TABLE public.customer_counts TO sqldump;
GRANT TRUNCATE ON TABLE public.customer_counts TO sqldump;
GRANT UPDATE ON TABLE public.customer_counts TO sqldump;
