-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.full_display_name(p_first text, p_last text)
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO app_readonly;
GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO sqldump;
