-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.invoice_number_seq
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON SEQUENCE public.invoice_number_seq TO app_readwrite;
GRANT USAGE ON SEQUENCE public.invoice_number_seq TO app_readwrite;
GRANT SELECT ON SEQUENCE public.invoice_number_seq TO sqldump;
GRANT UPDATE ON SEQUENCE public.invoice_number_seq TO sqldump;
GRANT USAGE ON SEQUENCE public.invoice_number_seq TO sqldump;
