-- Generated by sql-dump
-- Database: sqldump_test
-- Object: permissions:public.org
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.org TO app_readonly;
GRANT DELETE ON TABLE public.org TO app_readwrite;
GRANT INSERT ON TABLE public.org TO app_readwrite;
GRANT SELECT ON TABLE public.org TO app_readwrite;
GRANT UPDATE ON TABLE public.org TO app_readwrite;
GRANT DELETE ON TABLE public.org TO sqldump;
GRANT INSERT ON TABLE public.org TO sqldump;
GRANT REFERENCES ON TABLE public.org TO sqldump;
GRANT SELECT ON TABLE public.org TO sqldump;
GRANT TRIGGER ON TABLE public.org TO sqldump;
GRANT TRUNCATE ON TABLE public.org TO sqldump;
GRANT UPDATE ON TABLE public.org TO sqldump;
