-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: permissions:public.active_customers
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.active_customers TO app_readonly;
GRANT DELETE ON TABLE public.active_customers TO pgcarter;
GRANT INSERT ON TABLE public.active_customers TO pgcarter;
GRANT REFERENCES ON TABLE public.active_customers TO pgcarter;
GRANT SELECT ON TABLE public.active_customers TO pgcarter;
GRANT TRIGGER ON TABLE public.active_customers TO pgcarter;
GRANT TRUNCATE ON TABLE public.active_customers TO pgcarter;
GRANT UPDATE ON TABLE public.active_customers TO pgcarter;
