-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: permissions:public.audit_log
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.audit_log TO app_readonly;
GRANT DELETE ON TABLE public.audit_log TO pgcarter;
GRANT INSERT ON TABLE public.audit_log TO pgcarter;
GRANT REFERENCES ON TABLE public.audit_log TO pgcarter;
GRANT SELECT ON TABLE public.audit_log TO pgcarter;
GRANT TRIGGER ON TABLE public.audit_log TO pgcarter;
GRANT TRUNCATE ON TABLE public.audit_log TO pgcarter;
GRANT UPDATE ON TABLE public.audit_log TO pgcarter;
