-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: permissions:public.org
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT SELECT ON TABLE public.org TO app_readonly;
GRANT DELETE ON TABLE public.org TO app_readwrite;
GRANT INSERT ON TABLE public.org TO app_readwrite;
GRANT SELECT ON TABLE public.org TO app_readwrite;
GRANT UPDATE ON TABLE public.org TO app_readwrite;
GRANT DELETE ON TABLE public.org TO pgcarter;
GRANT INSERT ON TABLE public.org TO pgcarter;
GRANT REFERENCES ON TABLE public.org TO pgcarter;
GRANT SELECT ON TABLE public.org TO pgcarter;
GRANT TRIGGER ON TABLE public.org TO pgcarter;
GRANT TRUNCATE ON TABLE public.org TO pgcarter;
GRANT UPDATE ON TABLE public.org TO pgcarter;
