-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: permissions:public.schema
-- Generated: 2026-06-23T19:00:49.460689+00:00

GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO app_readonly;
GRANT CREATE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO pg_database_owner;
