-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.customer_audit
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE TRIGGER customer_audit AFTER INSERT OR DELETE OR UPDATE ON customer FOR EACH ROW EXECUTE FUNCTION audit_trigger();
