-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.customer_counts
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE MATERIALIZED VIEW public.customer_counts AS
SELECT org_id,
    count(*) AS total
   FROM customer
  GROUP BY org_id;
