"""Template-driven documentation rendering.

This layer is the *only* place Jinja2 is used, and it generates **no SQL**.
Templates are the source of truth for formatting; no Markdown is embedded in
Python. Templates are discovered dynamically: a missing template logs a warning
and is skipped rather than aborting the run.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment, FileSystemLoader, TemplateNotFound, select_autoescape

from sql_dump.logging_config import get_logger
from sql_dump.models import Inventory
from sql_dump.report import Report

log = get_logger(__name__)


def _doc_header(database: str, obj: str, timestamp: str) -> str:
    return (
        "<!--\n"
        "Generated by sql-dump\n"
        f"Database: {database}\n"
        f"Object: {obj}\n"
        f"Generated: {timestamp}\n"
        "-->\n"
    )


class DocumentationRenderer:
    """Renders Markdown documentation from a user-provided template directory."""

    def __init__(
        self,
        templates_dir: Path,
        docs_dir: Path,
        timestamp: str,
        report: Report,
    ) -> None:
        self.templates_dir = templates_dir
        self.docs_dir = docs_dir
        self.timestamp = timestamp
        self.report = report
        # autoescape=False: Markdown output, not HTML (per spec example).
        self.env = Environment(
            loader=FileSystemLoader(str(templates_dir)),
            autoescape=select_autoescape(enabled_extensions=(), default=False),
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
        )

    # -- discovery -----------------------------------------------------------
    def _has(self, template: str) -> bool:
        if (self.templates_dir / template).is_file():
            return True
        log.warning("Template '%s' not found; skipping", template)
        self.report.record_warning(f"Template '{template}' not found; documentation skipped")
        return False

    def _render(self, template: str, obj: str, out: Path, **context: Any) -> None:
        try:
            tmpl = self.env.get_template(template)
        except TemplateNotFound:
            log.warning("Template '%s' disappeared; skipping", template)
            self.report.record_warning(f"Template '{template}' not found")
            return
        body = tmpl.render(**self._base_context(), **context)
        out.parent.mkdir(parents=True, exist_ok=True)
        header = _doc_header(self._database_name, obj, self.timestamp)
        out.write_text(header + "\n" + body)
        self.report.record_file(out)

    # -- context -------------------------------------------------------------
    def _base_context(self) -> dict[str, Any]:
        return self._context_cache

    def render(self, inv: Inventory) -> None:
        self._database_name = inv.database.name
        self._context_cache = {
            "database": inv.database.to_dict(),
            "schemas": [s.to_dict() for s in inv.schemas],
            "tables": [t.to_dict() for t in inv.tables],
            "indexes": [i.to_dict() for i in inv.indexes],
            "views": [v.to_dict() for v in inv.views],
            "functions": [f.to_dict() for f in inv.functions],
            "triggers": [t.to_dict() for t in inv.triggers],
            "sequences": [s.to_dict() for s in inv.sequences],
            "extensions": [e.to_dict() for e in inv.extensions],
            "roles": [r.to_dict() for r in inv.roles],
            "permissions": [g.to_dict() for g in inv.grants],
            "relationships": [r.to_dict() for r in inv.relationships],
            "generated_at": self.timestamp,
        }

        # Top-level documents
        if self._has("index.md.j2"):
            self._render("index.md.j2", inv.database.name, self.docs_dir / "index.md")
        if self._has("database.md.j2"):
            self._render("database.md.j2", inv.database.name, self.docs_dir / "database.md")
        if self._has("roles.md.j2"):
            self._render("roles.md.j2", "roles", self.docs_dir / "roles.md")
        if self._has("permissions.md.j2"):
            self._render("permissions.md.j2", "permissions",
                         self.docs_dir / "permissions.md")

        self._render_schemas(inv)

    def _render_schemas(self, inv: Inventory) -> None:
        has_schema = self._has("schema.md.j2")
        has_table = self._has("table.md.j2")
        has_view = self._has("view.md.j2")
        has_func = self._has("function.md.j2")
        has_trig = self._has("trigger.md.j2")
        has_index = self._has("indexes.md.j2")

        for schema in inv.schemas:
            sname = schema.name
            root = self.docs_dir / "schemas" / sname
            tables = [t for t in inv.tables if t.schema == sname]
            views = [v for v in inv.views if v.schema == sname]
            funcs = [f for f in inv.functions if f.schema == sname]
            trigs = [t for t in inv.triggers if t.schema == sname]
            idxs = [i for i in inv.indexes if i.schema == sname]

            if has_schema:
                self._render(
                    "schema.md.j2", sname, root / "schema.md",
                    schema=schema.to_dict(),
                    schema_tables=[t.to_dict() for t in tables],
                    schema_views=[v.to_dict() for v in views],
                    schema_functions=[f.to_dict() for f in funcs],
                    schema_triggers=[t.to_dict() for t in trigs],
                    schema_indexes=[i.to_dict() for i in idxs],
                )
            if has_table:
                for t in tables:
                    self._render("table.md.j2", t.qualified_name,
                                 root / "tables" / f"{t.name}.md",
                                 table=t.to_dict(),
                                 table_indexes=[i.to_dict() for i in idxs
                                                if i.table == t.name])
            if has_view:
                for v in views:
                    self._render("view.md.j2", f"{sname}.{v.name}",
                                 root / "views" / f"{v.name}.md", view=v.to_dict())
            if has_func:
                for f in funcs:
                    self._render("function.md.j2", f"{sname}.{f.name}",
                                 root / "functions" / f"{f.name}.md",
                                 function=f.to_dict())
            if has_trig:
                for trig in trigs:
                    self._render("trigger.md.j2", f"{sname}.{trig.name}",
                                 root / "triggers" / f"{trig.name}.md",
                                 trigger=trig.to_dict())
            if has_index:
                self._render("indexes.md.j2", f"{sname} indexes",
                             root / "indexes" / "indexes.md",
                             schema=schema.to_dict(),
                             schema_indexes=[i.to_dict() for i in idxs])
