"""Shared SQL generation helpers.

This layer is intentionally free of any template engine: it produces SQL purely
from the metadata models. Output is deterministic so repeated runs against an
unchanged database yield byte-identical files (modulo the timestamp header).
"""

from __future__ import annotations

import re

_SIMPLE_IDENT = re.compile(r"^[a-z_][a-z0-9_]*$")
_RESERVED = {
    "user", "table", "select", "from", "where", "order", "group", "all",
    "default", "column", "constraint", "primary", "foreign", "references",
}


def quote_ident(name: str) -> str:
    """Quote an identifier only when required, matching PostgreSQL's rules."""
    if _SIMPLE_IDENT.match(name) and name not in _RESERVED:
        return name
    return '"' + name.replace('"', '""') + '"'


def qualified(schema: str, name: str) -> str:
    return f"{quote_ident(schema)}.{quote_ident(name)}"


def header(database: str, obj: str, timestamp: str) -> str:
    """Build the mandatory provenance header block."""
    return (
        "-- Generated by sql-dump\n"
        f"-- Database: {database}\n"
        f"-- Object: {obj}\n"
        f"-- Generated: {timestamp}\n"
    )


def with_header(database: str, obj: str, timestamp: str, body: str) -> str:
    return header(database, obj, timestamp) + "\n" + body.rstrip() + "\n"
