-- Generated by sql-dump
-- Database: sqldump_test
-- Object: apply
-- Generated: 2026-06-23T19:00:49.460689+00:00
-- Master script: applies the full schema in dependency order.

-- ======================================================================
-- Extensions
-- ======================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public VERSION '1.3';
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog VERSION '1.0';
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public VERSION '1.1';

-- ======================================================================
-- Roles
-- ======================================================================
DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_owner') THEN
        CREATE ROLE app_owner WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;
COMMENT ON ROLE app_owner IS 'Owns the application schema objects';

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readonly') THEN
        CREATE ROLE app_readonly WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readwrite') THEN
        CREATE ROLE app_readwrite WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;
GRANT app_readonly TO app_readwrite;

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sqldump') THEN
        CREATE ROLE sqldump WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION;
    END IF;
END $do$;

-- ======================================================================
-- Schemas
-- ======================================================================
CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION pg_database_owner;
COMMENT ON SCHEMA public IS 'standard public schema';

GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO app_readonly;
GRANT CREATE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO pg_database_owner;

-- ======================================================================
-- Sequences
-- ======================================================================
CREATE SEQUENCE IF NOT EXISTS public.audit_log_id_seq
    AS bigint
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1
    CACHE 1;
CREATE SEQUENCE IF NOT EXISTS public.invoice_number_seq
    AS bigint
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1000
    CACHE 1;

-- ======================================================================
-- Tables
-- ======================================================================
CREATE TABLE public.audit_log (
    id bigint DEFAULT nextval('audit_log_id_seq'::regclass) NOT NULL,
    table_name text NOT NULL,
    action text NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.org (
    id bigint GENERATED ALWAYS AS IDENTITY,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT org_pkey PRIMARY KEY (id),
    CONSTRAINT org_name_key UNIQUE (name)
);

COMMENT ON TABLE public.org IS 'Organisations';
COMMENT ON COLUMN public.org.name IS 'Unique display name';
CREATE TABLE public.customer (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    org_id bigint NOT NULL,
    email text NOT NULL,
    first_name text,
    last_name text,
    full_name text GENERATED ALWAYS AS (((COALESCE(first_name, ''::text) || ' '::text) || COALESCE(last_name, ''::text))) STORED,
    balance numeric(12,2) DEFAULT 0 NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id),
    CONSTRAINT customer_email_key UNIQUE (email),
    CONSTRAINT customer_org_id_fkey FOREIGN KEY (org_id) REFERENCES org(id) ON DELETE CASCADE,
    CONSTRAINT customer_balance_chk CHECK (balance >= 0::numeric),
    CONSTRAINT customer_status_chk CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'banned'::text]))
);

COMMENT ON TABLE public.customer IS 'Customers belonging to an organisation';

-- ======================================================================
-- Sequence ownership
-- ======================================================================
ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;

-- ======================================================================
-- Indexes
-- ======================================================================
CREATE INDEX customer_active_idx ON customer USING btree (email) WHERE status = 'active'::text;
CREATE INDEX customer_lower_email_idx ON customer USING btree (lower(email));
CREATE INDEX customer_org_idx ON customer USING btree (org_id);
CREATE UNIQUE INDEX org_lower_name_uidx ON org USING btree (lower(name));

-- ======================================================================
-- Views
-- ======================================================================
CREATE VIEW public.active_customers AS
SELECT c.id,
    c.email,
    o.name AS org_name
   FROM customer c
     JOIN org o ON o.id = c.org_id
  WHERE c.status = 'active'::text;

COMMENT ON VIEW public.active_customers IS 'Active customers with their organisation name';
CREATE MATERIALIZED VIEW public.customer_counts AS
SELECT org_id,
    count(*) AS total
   FROM customer
  GROUP BY org_id;

-- ======================================================================
-- Functions
-- ======================================================================
CREATE OR REPLACE FUNCTION public.audit_trigger()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    INSERT INTO audit_log (table_name, action)
    VALUES (TG_TABLE_NAME, TG_OP);
    RETURN NEW;
END;
$function$;
CREATE OR REPLACE PROCEDURE public.deactivate_customer(IN p_id bigint)
 LANGUAGE plpgsql
AS $procedure$
BEGIN
    UPDATE customer SET status = 'inactive' WHERE id = p_id;
END;
$procedure$;
CREATE OR REPLACE FUNCTION public.full_display_name(p_first text, p_last text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$
    SELECT trim(coalesce(p_first, '') || ' ' || coalesce(p_last, ''));
$function$;

-- ======================================================================
-- Triggers
-- ======================================================================
CREATE TRIGGER customer_audit AFTER INSERT OR DELETE OR UPDATE ON customer FOR EACH ROW EXECUTE FUNCTION audit_trigger();

-- ======================================================================
-- Privileges
-- ======================================================================
GRANT SELECT (email) ON TABLE public.customer TO app_readonly;
GRANT SELECT (id) ON TABLE public.customer TO app_readonly;
GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO PUBLIC;
GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO app_readonly;
GRANT EXECUTE ON FUNCTION public.full_display_name(p_first text, p_last text) TO sqldump;
GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO app_readonly;
GRANT CREATE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO pg_database_owner;
GRANT SELECT ON SEQUENCE public.invoice_number_seq TO app_readwrite;
GRANT USAGE ON SEQUENCE public.invoice_number_seq TO app_readwrite;
GRANT SELECT ON SEQUENCE public.invoice_number_seq TO sqldump;
GRANT UPDATE ON SEQUENCE public.invoice_number_seq TO sqldump;
GRANT USAGE ON SEQUENCE public.invoice_number_seq TO sqldump;
GRANT SELECT ON TABLE public.active_customers TO app_readonly;
GRANT DELETE ON TABLE public.active_customers TO sqldump;
GRANT INSERT ON TABLE public.active_customers TO sqldump;
GRANT REFERENCES ON TABLE public.active_customers TO sqldump;
GRANT SELECT ON TABLE public.active_customers TO sqldump;
GRANT TRIGGER ON TABLE public.active_customers TO sqldump;
GRANT TRUNCATE ON TABLE public.active_customers TO sqldump;
GRANT UPDATE ON TABLE public.active_customers TO sqldump;
GRANT SELECT ON TABLE public.audit_log TO app_readonly;
GRANT DELETE ON TABLE public.audit_log TO sqldump;
GRANT INSERT ON TABLE public.audit_log TO sqldump;
GRANT REFERENCES ON TABLE public.audit_log TO sqldump;
GRANT SELECT ON TABLE public.audit_log TO sqldump;
GRANT TRIGGER ON TABLE public.audit_log TO sqldump;
GRANT TRUNCATE ON TABLE public.audit_log TO sqldump;
GRANT UPDATE ON TABLE public.audit_log TO sqldump;
GRANT SELECT ON TABLE public.customer TO app_readonly;
GRANT DELETE ON TABLE public.customer TO app_readwrite;
GRANT INSERT ON TABLE public.customer TO app_readwrite;
GRANT SELECT ON TABLE public.customer TO app_readwrite;
GRANT UPDATE ON TABLE public.customer TO app_readwrite;
GRANT DELETE ON TABLE public.customer TO sqldump;
GRANT INSERT ON TABLE public.customer TO sqldump;
GRANT REFERENCES ON TABLE public.customer TO sqldump;
GRANT SELECT ON TABLE public.customer TO sqldump;
GRANT TRIGGER ON TABLE public.customer TO sqldump;
GRANT TRUNCATE ON TABLE public.customer TO sqldump;
GRANT UPDATE ON TABLE public.customer TO sqldump;
GRANT SELECT ON TABLE public.customer_counts TO app_readonly;
GRANT DELETE ON TABLE public.customer_counts TO sqldump;
GRANT INSERT ON TABLE public.customer_counts TO sqldump;
GRANT REFERENCES ON TABLE public.customer_counts TO sqldump;
GRANT SELECT ON TABLE public.customer_counts TO sqldump;
GRANT TRIGGER ON TABLE public.customer_counts TO sqldump;
GRANT TRUNCATE ON TABLE public.customer_counts TO sqldump;
GRANT UPDATE ON TABLE public.customer_counts TO sqldump;
GRANT SELECT ON TABLE public.org TO app_readonly;
GRANT DELETE ON TABLE public.org TO app_readwrite;
GRANT INSERT ON TABLE public.org TO app_readwrite;
GRANT SELECT ON TABLE public.org TO app_readwrite;
GRANT UPDATE ON TABLE public.org TO app_readwrite;
GRANT DELETE ON TABLE public.org TO sqldump;
GRANT INSERT ON TABLE public.org TO sqldump;
GRANT REFERENCES ON TABLE public.org TO sqldump;
GRANT SELECT ON TABLE public.org TO sqldump;
GRANT TRIGGER ON TABLE public.org TO sqldump;
GRANT TRUNCATE ON TABLE public.org TO sqldump;
GRANT UPDATE ON TABLE public.org TO sqldump;
