-- Generated by sql-dump
-- Database: sqldump_test
-- Object: sqldump_test
-- Generated: 2026-06-23T19:00:49.460689+00:00

-- Database: sqldump_test
-- Version: 16.14
-- Owner: sqldump
--
-- Recreate with (run from an administrative connection):
CREATE DATABASE sqldump_test
    WITH OWNER = sqldump
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8';
