-- Generated by sql-dump
-- Database: sqldump_test
-- Object: roles
-- Generated: 2026-06-23T19:00:49.460689+00:00

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_owner') THEN
        CREATE ROLE app_owner WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;
COMMENT ON ROLE app_owner IS 'Owns the application schema objects';

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readonly') THEN
        CREATE ROLE app_readonly WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readwrite') THEN
        CREATE ROLE app_readwrite WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOREPLICATION;
    END IF;
END $do$;
GRANT app_readonly TO app_readwrite;

DO $do$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'sqldump') THEN
        CREATE ROLE sqldump WITH SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN REPLICATION;
    END IF;
END $do$;
