-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.audit_log_id_seq
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE SEQUENCE IF NOT EXISTS public.audit_log_id_seq
    AS bigint
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1
    CACHE 1;
ALTER SEQUENCE public.audit_log_id_seq OWNED BY public.audit_log.id;
