-- Seed schema for sql-dump integration / e2e tests.
-- Exercises every asset category the extractor supports:
-- extensions, roles, schemas, tables (identity + generated + check/fk/unique),
-- sequences, indexes (incl. partial & expression), views, materialized views,
-- functions, procedures, triggers, comments, and privileges.

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_owner') THEN
        CREATE ROLE app_owner NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readonly') THEN
        CREATE ROLE app_readonly NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_readwrite') THEN
        CREATE ROLE app_readwrite NOLOGIN;
    END IF;
END
$$;

GRANT app_readonly TO app_readwrite;
COMMENT ON ROLE app_owner IS 'Owns the application schema objects';

-- ---------------------------------------------------------------------------
-- Schema
-- ---------------------------------------------------------------------------
COMMENT ON SCHEMA public IS 'standard public schema';
GRANT USAGE ON SCHEMA public TO app_readonly;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------
CREATE TABLE org (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name        text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now()
);
COMMENT ON TABLE org IS 'Organisations';
COMMENT ON COLUMN org.name IS 'Unique display name';

CREATE TABLE customer (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id      bigint NOT NULL REFERENCES org (id) ON DELETE CASCADE,
    email       text NOT NULL,
    first_name  text,
    last_name   text,
    full_name   text GENERATED ALWAYS AS (
                    coalesce(first_name, '') || ' ' || coalesce(last_name, '')
                ) STORED,
    balance     numeric(12,2) NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'active',
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customer_email_key UNIQUE (email),
    CONSTRAINT customer_status_chk CHECK (status IN ('active', 'inactive', 'banned')),
    CONSTRAINT customer_balance_chk CHECK (balance >= 0)
);
COMMENT ON TABLE customer IS 'Customers belonging to an organisation';

CREATE TABLE audit_log (
    id          bigserial PRIMARY KEY,
    table_name  text NOT NULL,
    action      text NOT NULL,
    at          timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Standalone sequence
-- ---------------------------------------------------------------------------
CREATE SEQUENCE invoice_number_seq START 1000 INCREMENT 1;

-- ---------------------------------------------------------------------------
-- Indexes (plain, partial, expression, unique)
-- ---------------------------------------------------------------------------
CREATE INDEX customer_org_idx ON customer (org_id);
CREATE INDEX customer_active_idx ON customer (email) WHERE status = 'active';
CREATE INDEX customer_lower_email_idx ON customer (lower(email));
CREATE UNIQUE INDEX org_lower_name_uidx ON org (lower(name));

-- ---------------------------------------------------------------------------
-- Views and materialized views
-- ---------------------------------------------------------------------------
CREATE VIEW active_customers AS
    SELECT c.id, c.email, o.name AS org_name
    FROM customer c
    JOIN org o ON o.id = c.org_id
    WHERE c.status = 'active';
COMMENT ON VIEW active_customers IS 'Active customers with their organisation name';

CREATE MATERIALIZED VIEW customer_counts AS
    SELECT org_id, count(*) AS total
    FROM customer
    GROUP BY org_id;

-- ---------------------------------------------------------------------------
-- Functions and a procedure
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION full_display_name(p_first text, p_last text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT trim(coalesce(p_first, '') || ' ' || coalesce(p_last, ''));
$$;
COMMENT ON FUNCTION full_display_name(text, text) IS 'Compose a display name';

CREATE OR REPLACE FUNCTION audit_trigger()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    INSERT INTO audit_log (table_name, action)
    VALUES (TG_TABLE_NAME, TG_OP);
    RETURN NEW;
END;
$$;

CREATE OR REPLACE PROCEDURE deactivate_customer(p_id bigint)
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE customer SET status = 'inactive' WHERE id = p_id;
END;
$$;

-- ---------------------------------------------------------------------------
-- Trigger
-- ---------------------------------------------------------------------------
CREATE TRIGGER customer_audit
    AFTER INSERT OR UPDATE OR DELETE ON customer
    FOR EACH ROW
    EXECUTE FUNCTION audit_trigger();

-- ---------------------------------------------------------------------------
-- Privileges
-- ---------------------------------------------------------------------------
GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_readonly;
GRANT SELECT, INSERT, UPDATE, DELETE ON customer, org TO app_readwrite;
GRANT SELECT (id, email) ON customer TO app_readonly;
GRANT USAGE, SELECT ON SEQUENCE invoice_number_seq TO app_readwrite;
GRANT EXECUTE ON FUNCTION full_display_name(text, text) TO app_readonly;
