-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: public.invoice_number_seq
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE SEQUENCE IF NOT EXISTS public.invoice_number_seq
    AS bigint
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START WITH 1000
    CACHE 1;
