-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.audit_log
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE TABLE public.audit_log (
    id bigint DEFAULT nextval('audit_log_id_seq'::regclass) NOT NULL,
    table_name text NOT NULL,
    action text NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
