-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.customer_lower_email_idx
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE INDEX customer_lower_email_idx ON customer USING btree (lower(email));
