-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.customer_active_idx
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE INDEX customer_active_idx ON customer USING btree (email) WHERE status = 'active'::text;
