-- Generated by sql-dump
-- Database: sqldump_test
-- Object: public.org_lower_name_uidx
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE UNIQUE INDEX org_lower_name_uidx ON org USING btree (lower(name));
