-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: pgcarter_test
-- Generated: 2026-06-23T19:00:49.460689+00:00

-- Database: pgcarter_test
-- Version: 16.14
-- Owner: pgcarter
--
-- Recreate with (run from an administrative connection):
CREATE DATABASE pgcarter_test
    WITH OWNER = pgcarter
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8';
