-- Generated by pgcarter
-- Database: pgcarter_test
-- Object: public
-- Generated: 2026-06-23T19:00:49.460689+00:00

CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION pg_database_owner;
COMMENT ON SCHEMA public IS 'standard public schema';

GRANT USAGE ON SCHEMA public TO PUBLIC;
GRANT USAGE ON SCHEMA public TO app_readonly;
GRANT CREATE ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO pg_database_owner;
